// flow-typed signature: 0083730478c71a25c2d14e00f4f974bd
// flow-typed version: <<STUB>>/@textpress/babel-preset-textpress_v>=0.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@textpress/babel-preset-textpress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@textpress/babel-preset-textpress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@textpress/babel-preset-textpress/index' {
  declare module.exports: $Exports<'@textpress/babel-preset-textpress'>;
}
declare module '@textpress/babel-preset-textpress/index.js' {
  declare module.exports: $Exports<'@textpress/babel-preset-textpress'>;
}
