// flow-typed signature: 43e951349e19876ba258869f4bdb2265
// flow-typed version: <<STUB>>/@textpress/extendable-error_v>=0.4.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@textpress/extendable-error'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@textpress/extendable-error' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@textpress/extendable-error/lib/extendable-error' {
  declare module.exports: any;
}

// Filename aliases
declare module '@textpress/extendable-error/lib/extendable-error.js' {
  declare module.exports: $Exports<'@textpress/extendable-error/lib/extendable-error'>;
}
