// flow-typed signature: 7cbd93559a884bf7b93db61d1071d593
// flow-typed version: <<STUB>>/node-config_v^0.0.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'node-config/index' {
  declare module.exports: $Exports<'node-config'>;
}
declare module 'node-config/index.js' {
  declare module.exports: $Exports<'node-config'>;
}
